# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happiness', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='favorite',
            field=models.ManyToManyField(related_name='favoritesfrom', to='happiness.User'),
        ),
    ]
